# Generated by Django 4.2.7 on 2023-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Femea', 'Femea')], max_length=10)),
            ],
        ),
    ]
